### ISSUE TITLE
Non-English Companies

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-companies#15]
Reports of company names that are non-standard not being found.

**Comment by spencerfinnell** [comment]
https://github.com/Astoundify/wp-job-manager-companies/blob/master/wp-job-manager-companies.php#L245

**Comment by spencerfinnell** [comment]
Also fails on numbers.

**Comment by fezode** [comment]
For it to work on non-English letters you could use "array" instead of "range", for example (Arabic letters):

foreach ( array('ا','ب','ت','ث') as $letter ) {

And you are using "strtoupper" which will not work for Unicode characters, instead you should use mb_strtoupper

**Comment by spencerfinnell** [comment]
https://github.com/Astoundify/wp-job-manager-companies/issues/19#issuecomment-322206961
