### ISSUE TITLE
Override Canonical URL

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-companies#18]
http://craiget.com/blog/override-relcanonical-in-wordpress/

**Comment by turtlepod** [comment]
WordPress don't have canonical url for archive pages.
And technically this is a "fake" archive pages. So, I'm not sure we need to add this.

**Comment by spencerfinnell** [comment]
https://github.com/Astoundify/wp-job-manager-companies/issues/19#issuecomment-322206961
