### ISSUE TITLE
URL Edit?

### ISSUE THREAD

**Issue by fsl-** [Astoundify/wp-job-manager-companies#6]
1- Is it possible to change company name separator from + to a hyphen?

e.g. for CGI Group, the URL will be www.website.com/companies/CGI+Group
Can it be changed to www.website.com/companies/CGI-Group ?

2- Also the company pages are case sensitive, can we do something about that?

**Comment by turtlepod** [comment]
This is probably not possible.
WordPress do this by having "slug" for permalink.
post meta do not have this.

the solution, is to create new meta for company slug, or move to custom taxonomy.

**Comment by spencerfinnell** [comment]
https://github.com/Astoundify/wp-job-manager-companies/issues/19#issuecomment-322206961
